name: Compilar APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java 8 (Versión nativa de MNML)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Aceptar licencias del SDK de Android automáticamente
        run: |
          mkdir -p ${ANDROID_HOME}/licenses
          echo -e "\n893a5cd8e1c6392d9c74d8e74d3752e9fc534316\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > ${ANDROID_HOME}/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > ${ANDROID_HOME}/licenses/android-sdk-preview-license

      - name: Dar permisos de ejecución al compilador
        run: chmod +x gradlew

      - name: Limpiar y Compilar Proyecto Original
        run: ./gradlew clean assembleDebug --stacktrace
        
