name: Compilar APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Configurar Java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Forzar compatibilidad con Java moderno en el proyecto
        run: |
          chmod +x gradlew
          sed -i 's/compileSdkVersion 28/compileSdkVersion 34/g' app/build.gradle
          sed -i 's/targetSdkVersion 28/targetSdkVersion 34/g' app/build.gradle
          ./gradlew wrapper --gradle-version 8.4

      - name: Compilar con Gradle
        run: ./gradlew assembleDebug

      - name: Guardar APK obtenido
        uses: actions/upload-artifact@v4
        with:
          name: mnml-apk
          path: app/build/outputs/apk/debug/*.apk
          
